### ISSUE TITLE
zsh: command not found: dotIssue: ...

### ISSUE THREAD

**Issue by haibert** [sverweij/dependency-cruiser#570]
### Expected Behavior

Graph to be created

### Current Behavior

when I run 

dependency-cruise -x "^node_modules" -T dot src | dot -T svg > dependencygraph.svg

I get 

zsh: command not found: dot
``` console
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at writeToStdOut (/usr/local/lib/node_modules/dependency-cruiser/src/cli/utl/io.js:36:20)
    at Object.write (/usr/local/lib/node_modules/dependency-cruiser/src/cli/utl/io.js:44:5)
    at runCruise (/usr/local/lib/node_modules/dependency-cruiser/src/cli/index.js:124:6)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

### Steps to Reproduce (for bugs)

1. Install dependency-cruiser
2. run dependency-cruise -x "^node_modules" -T dot src | dot -T svg > dependencygraph.svg

### Context

I am trying to create a dependency graph for my react app

### Your Environment

- Version used: "^11.3.1"
- Node version: v16.13.0
- Operating System and version: Monterey M1 Mac
- Link to your project: its a private repository

**Comment by sverweij** [comment]
Hi @haibert it seems that on your machine `zsh` can't find the `dot` command - which is part of the [GraphViz](https://graphviz.org) suite. A likely cause is that it isn't installed on your machine. On a Mac you can install it e.g. with homebrew (`brew install graphviz`) after you should be set.

**Comment by aladdin-add** [comment]
same issue on macos. it won't hurt to add a prerequisites in the readme.

**Comment by liuliangsir** [comment]
Same issue on MacOS 13.0 Beta(22A5311f)
